apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: addtional-controller
  namespace: openshift-ingress-operator
spec:
  clientTLS:                                  # IngressController와 연결된 Route의 기본 CA인증서
    clientCA:
      name: ""
    clientCertificatePolicy: ""
  domain: test.d.ocp.local                    # IngressController의 기본 도메인
  endpointPublishingStrategy:                 # IngressController의 엔드포인트 게시전략
    type: HostNetwork
    hostNetwork:                              # 노드 추가 없이 호스트의 여분 포트를 사용
      httpPort: 33080
      httpsPort: 33443
      statsPort: 32936
  tlsSecurityProfile:                         # TLS 최소 버전 및 연결용 Ciphers를 지정
    type: Old
    old: {}
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ""
  idleConnectionTerminationPolicy: Deferred
  replicas: 2
  routeSelector:                            # 이 라벨을 갖고 있는 Route에 대해서만 IngressController와 연결
    matchLabels:
      route: additional
  tuningOptions:
    reloadInterval: 0s
    maxConnections: -1
    clientFinTimeout: 1s
    clientTimeout: 300s
    headerBufferBytes: 65536
    headerBufferMaxRewriteBytes: 32768
    serverFinTimeout: 1s
    serverTimeout: 30s
    threadCount: 4
    tlsInspectDelay: 5s
    tunnelTimeout: 1h
  logging:                                    # 엑세스 로깅을 가능하게 처리
    access:
      destination:
        type: Container
  unsupportedConfigOverrides: null
