apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: example
  namespace: default
spec:
  scaleTargetRef:
    kind: DeploymentConfig
    name: test-httpd
    apiVersion: apps.openshift.io/v1
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageValue: 100m
          type: AverageValue

