apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: thin-csi
parameters:			
  StoragePolicyName: openshift-storage-policy-d-jdcnw
provisioner: csi.vsphere.vmware.com
reclaimPolicy: Delete	
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer	
