apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-viewer
  namespace: guest04
rules:
- apiGroups:
  - ""
  resources:
  - replicationcontrollers
  - pods
  - pods/exec
  - pods/log
  - services
  - configmaps
  - secrets
  - persistentvolumeclaims
  - events
  - namespaces
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - edit
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - statefulsets
  - replicasets
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - apps.openshift.io
  resources:
  - deploymentconfigs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
- apiGroups:
  - build.openshift.io
  resources:
  - builds
  - buildconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - metrics.k8s.io
  resources:
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - workspace.devfile.io
  resources:
  - devworkspaces
  verbs:
  - create
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: guest04-viewer
rules:
  - apiGroups:
    - project.openshift.io
    resources:
    - projects
    resourceNames:
    - guest04
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - namespaces
    resourceNames:
    - guest04
    verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: guest04-viewer-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: guest04-viewer
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: guest04
