apiVersion: v1
kind: ConfigMap
metadata:
  name: py-file
data:
  app.py: |
    import http.server as SimpleHTTPServer
    import socketserver as SocketServer
    import logging
    import os

    PORT = int(os.environ.get("PORT", 3000))

    class GetHandler(
        SimpleHTTPServer.SimpleHTTPRequestHandler
    ):

        def do_GET(self):
            logging.error(self.headers)
            SimpleHTTPServer.SimpleHTTPRequestHandler.do_GET(self)


    Handler = GetHandler
    httpd = SocketServer.TCPServer(("", PORT), Handler)

    httpd.serve_forever()
