apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  finalizers:
  - kubernetes.io/pv-protection
  name: openjdk-test01-v2-log-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /data/nfs/application/kblife/openjdk-test01-v2
    server: 192.168.7.40
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
