apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openjdk-test01-v2-log-pvc
  namespace: kblife
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: openjdk-test01-v2-log-pv
